CREATE TABLE BOARD
(
   NO         NUMBER PRIMARY KEY,
   REFNO       NUMBER,
   SUBJECT     VARCHAR2 (100),
   CONTENT     VARCHAR2 (1000),
   PASS        VARCHAR2 (30),
   WIRTER      VARCHAR2 (50),
   READCOUNT   NUMBER,
   REGDATE     DATE,
   EMAIL       VARCHAR2 (100)
);

CREATE SEQUENCE BOARD_SEQ
START WITH 1
INCREMENT BY 1
MAXVALUE 999999
MINVALUE 1
NOCYCLE 
CACHE 20;
